### ISSUE TITLE
Use a local SQS instance

### ISSUE THREAD

**Issue by viniciusd** [dashbitco/broadway_sqs#60] opened 2021-03-11 01:40 UTC
Hello there!

I started trying Broadway [and BroadwaySqs] Today. Whenever I use SQS, I try using a local instance via [ElasticMQ](https://github.com/softwaremill/elasticmq) for development purposes via docker (`docker run -p 9324:9324 -p 9325:9325 softwaremill/elasticmq-native`).

Is it possible to point to a local ElasticMQ instance using BroadwaySqs? I don't see anything related in the docs.

I tried setting the queue_url parameter to `http://localhost:9324/<queue_name>`, but I got the following traceback:
```
22:14:43.438 [error] GenServer ExAws.Config.AuthCache terminating
** (RuntimeError) Instance Meta Error: {:error, %{reason: :timeout}}

You tried to access the AWS EC2 instance meta, but it could not be reached.
This happens most often when trying to access it from your local computer,
which happens when environment variables are not set correctly prompting
ExAws to fallback to the Instance Meta.

Please check your key config and make sure they're configured correctly:

For Example:
ExAws.Config.new(:s3)
ExAws.Config.new(:dynamodb)

    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:29: ExAws.InstanceMeta.request/2
    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:66: ExAws.InstanceMeta.instance_role_credentials/1
    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:74: ExAws.InstanceMeta.security_credentials/1
    (ex_aws 2.1.7) lib/ex_aws/config/auth_cache.ex:83: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws 2.1.7) lib/ex_aws/config/auth_cache.ex:44: ExAws.Config.AuthCache.handle_call/3
    (stdlib 3.11.2) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib 3.11.2) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from WorldTemp.TempProcessor.Broadway.Producer_0): {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: "sqs.us-east-1.amazonaws.com", http_client: ExAws.Request.Hackney, json_codec: Jason, normalize_path: true, port: 443, region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}
State: ExAws.Config.AuthCache
Client WorldTemp.TempProcessor.Broadway.Producer_0 is alive

    (stdlib 3.11.2) gen.erl:167: :gen.do_call/4
    (elixir 1.10.2) lib/gen_server.ex:1020: GenServer.call/3
    (ex_aws 2.1.7) lib/ex_aws/config.ex:84: ExAws.Config.retrieve_runtime_value/2
    (elixir 1.10.2) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.10.2) lib/enum.ex:3686: Enumerable.List.reduce/3
    (elixir 1.10.2) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.10.2) lib/enum.ex:959: Enum.find/3
    (ex_aws 2.1.7) lib/ex_aws/config.ex:71: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1

22:14:43.448 [error] GenServer WorldTemp.TempProcessor.Broadway.Producer_0 terminating
** (stop) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: "sqs.us-east-1.amazonaws.com", http_client: ExAws.Request.Hackney, json_codec: Jason, normalize_path: true, port: 443, region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}, 30000)
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Instance Meta Error: {:error, %{reason: :timeout}}
 ```

I noticed it is assuming the region `us-east-1`, so I tried adding the region parameter as part of the producer config (`config: [region: "elasticmq"]`):

```
22:17:36.260 [error] GenServer ExAws.Config.AuthCache terminating
** (RuntimeError) Instance Meta Error: {:error, %{reason: :timeout}}

You tried to access the AWS EC2 instance meta, but it could not be reached.
This happens most often when trying to access it from your local computer,
which happens when environment variables are not set correctly prompting
ExAws to fallback to the Instance Meta.

Please check your key config and make sure they're configured correctly:

For Example:
ExAws.Config.new(:s3)
ExAws.Config.new(:dynamodb)

    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:29: ExAws.InstanceMeta.request/2
    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:66: ExAws.InstanceMeta.instance_role_credentials/1
    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:74: ExAws.InstanceMeta.security_credentials/1
    (ex_aws 2.1.7) lib/ex_aws/config/auth_cache.ex:83: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws 2.1.7) lib/ex_aws/config/auth_cache.ex:44: ExAws.Config.AuthCache.handle_call/3
    (stdlib 3.11.2) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib 3.11.2) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from WorldTemp.TempProcessor.Broadway.Producer_0): {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: nil, http_client: ExAws.Request.Hackney, json_codec: Jason, normalize_path: true, port: 443, region: "elasticmq", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}
State: ExAws.Config.AuthCache
Client WorldTemp.TempProcessor.Broadway.Producer_0 is alive

    (stdlib 3.11.2) gen.erl:167: :gen.do_call/4
    (elixir 1.10.2) lib/gen_server.ex:1020: GenServer.call/3
    (ex_aws 2.1.7) lib/ex_aws/config.ex:84: ExAws.Config.retrieve_runtime_value/2
    (elixir 1.10.2) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.10.2) lib/enum.ex:3686: Enumerable.List.reduce/3
    (elixir 1.10.2) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.10.2) lib/enum.ex:959: Enum.find/3
    (ex_aws 2.1.7) lib/ex_aws/config.ex:71: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1

22:17:36.272 [error] GenServer WorldTemp.TempProcessor.Broadway.Producer_0 terminating
** (stop) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: nil, http_client: ExAws.Request.Hackney, json_codec: Jason, normalize_path: true, port: 443, region: "elasticmq", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}, 30000)
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Instance Meta Error: {:error, %{reason: :timeout}}
```

I see host is now nil, yet I could not go much further. I tried setting scheme to `http://` instead of `https://` but it had no effect.

Then I tried following the source code, which led me to https://github.com/dashbitco/broadway_sqs/blob/master/lib/broadway_sqs/ex_aws_client.ex#L28
```elixir
  @impl true
  def receive_messages(demand, opts) do
    receive_messages_opts = build_receive_messages_opts(opts, demand)

    opts.queue_url
    |> ExAws.SQS.receive_message(receive_messages_opts)
    |> ExAws.request(opts.config)
    |> wrap_received_messages(opts.ack_ref)
  end
```

Then I checked [ExAws.SQS.receive_message/2](https://github.com/ex-aws/ex_aws_sqs/blob/master/lib/ex_aws/sqs.ex#L379), which relies on [ExAws.SQS.request/3](https://github.com/ex-aws/ex_aws_sqs/blob/master/lib/ex_aws/sqs.ex#L491). This might not be only a BroadwaySQS issue because I don't see how would ExAws make the AWS host configurable.

Just so I wrap it up with a question: Is it possible to point BroadwaySQS to a local ElasticMQ instance?

P.S.: I haven't touched any Elixir code in many months, so I am probably missing some important detail here

**Comment by viniciusd** [comment] 2021-03-11 01:52
Also tried:
```elixir
          config: [
            scheme: "http://",
            host: "localhost",
            port: "9324",
            region: "elasticmq"
          ] 
```

I see those parameters reflect into the error message, but no success either.

**Comment by josevalim** [comment] 2021-03-11 06:41
Please show us our versions and Broadway configuration. AFAIK this is possible and it has been improved lately, [see here](https://github.com/ex-aws/ex_aws_sqs/pull/9).

**Comment by josevalim** [comment] 2021-03-11 06:45
It may also be that your queue_url has to be http://localhost:9324/queue/wl-test-queue. Make sure you can properly curl the endpoints.

**Comment by viniciusd** [comment] 2021-03-11 11:32
> Please show us our versions 

I am using the following versions:
```
* ex_aws_sqs 3.2.1 (Hex package) (mix)
  locked at 3.2.1 (ex_aws_sqs) ae77e296
  ok
* broadway_sqs 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (broadway_sqs) a17981e2
  ok
* ex_aws 2.1.7 (Hex package) (mix)
  locked at 2.1.7 (ex_aws) 7ce83285
  ok
* broadway 0.6.2 (Hex package) (mix)
  locked at 0.6.2 (broadway) f4f93704
  ok
```

> and Broadway configuration. 

```elixir
  def start_link(_opts) do
    Broadway.start_link(__MODULE__,
      name: __MODULE__,
      producer: [
        module: {BroadwaySQS.Producer,
          queue_url: "http://localhost:9324/hi",
          config: [
            scheme: "http://",
            host: "localhost",
            port: "9324",
            region: "elasticmq"
          ] 
        },
        rate_limiting: [
          allowed_messages: 60,
          interval: 60_000
        ]
      ],
      processors: [
        default: [concurrency: 5]
      ]
    )
  end
```

> AFAIK this is possible and it has been improved lately, [see here](https://github.com/ex-aws/ex_aws_sqs/pull/9).

This PR seems very interesting and definitely related. I see they are using the following configuration:
```elixir
config :ex_aws, :sqs,
  access_key_id: "foo",
  secret_access_key: "bar",
  scheme: "http://",
  host: "localhost",
  port: 9324,
  region: "us-east-1"
```
I would assume I am doing all right by setting those parameters.

**Comment by viniciusd** [comment] 2021-03-11 11:36
> It may also be that your queue_url has to be http://localhost:9324/queue/wl-test-queue. Make sure you can properly curl the endpoints.

You are absolutely right. The path should be `/queue/<queue_name>`. Just tried it with curl: `curl 'http://localhost:9324/queue/hi?Action=SendMessage&MessageBody=Foobar'`

But I am still getting the same error message when using the right URL.

**Comment by msaraiva** [comment] 2021-03-11 13:10
Hi @viniciusd!

This config works for me:

```elixir
    queue_url: "http://localhost:9324/queue/ptec",
    config: [
      scheme: "http://",
      host: "localhost",
      port: 9324
    ]
```

Here's the full source of the example I tried:

```elixir
# example.exs

defmodule MyBroadway do
  use Broadway

  alias Broadway.Message

  def handle_message(_, %Message{data: _data} = message, _context) do
    message
  end

  def handle_batch(_, messages, _info, _context) do
    data_list = messages |> Enum.map(fn e -> {e.data, e.metadata} end)
    IO.inspect(data_list, label: "SQS: Got batch")
    messages
  end
end

# Run
Broadway.start_link(MyBroadway,
  name: MyBroadway,
  producer: [
    module: {BroadwaySQS.Producer,
      wait_time_seconds: 0,
      max_number_of_messages: 10,
      queue_url: "http://localhost:9324/queue/ptec",
      config: [
        scheme: "http://",
        host: "localhost",
        port: 9324
      ]
    },
    concurrency: 60,
  ],
  processors: [default: [concurrency: 20]],
  batchers: [
    default: [
      batch_size: 10,
      concurrency: 8,
    ],
  ]
)

Process.sleep(:infinity)

```

I use the following script to send some sample messages to the queue:

```elixir
# send_messages.exs

tasks =
  1..1000
  |> Enum.chunk_every(10)
  |> Enum.map(fn numbers ->
    messages = Enum.map(numbers, fn i ->
      [
        id: "#{i}",
        message_body: "Mensagem #{i}",
        delay_seconds: 1,
      ]
    end)
    Task.async(fn ->
      ExAws.SQS.send_message_batch("http://localhost:9324/queue/ptec", messages)
      |> ExAws.request([
        scheme: "http://",
        host: "localhost",
        port: 9324
      ])
    end)
  end)

Task.yield_many(tasks, 30_000)
|> Enum.map(fn {_task, {:ok, value}} -> value end)
|> IO.inspect
```

You can run both scripts using:

```
elixir -S mix run send_messages.exs
```

```
elixir -S mix run example.exs
```

**Comment by viniciusd** [comment] 2021-03-11 15:02
Thank you for your examples @msaraiva. So it is definitely a problem with my setup.

Not only that, but you showed me that my problem is not related to BroadwaySqs at all, given not even the `send_messages.exs` script is succeeding. The script gives me the same error messages I was getting with Broadway.

One thing that caught my attention: even if I set the region to `elasticmq` explicitly in the `send_messages.exs` script, the first error messages shows `us-east-1`

```
○ elixir -S mix run send_messages.exs                                                                                                                                                                                                                                       [i]

11:58:55.693 [error] GenServer ExAws.Config.AuthCache terminating
** (RuntimeError) Instance Meta Error: {:error, %{reason: :timeout}}

You tried to access the AWS EC2 instance meta, but it could not be reached.
This happens most often when trying to access it from your local computer,
which happens when environment variables are not set correctly prompting
ExAws to fallback to the Instance Meta.

Please check your key config and make sure they're configured correctly:

For Example:
ExAws.Config.new(:s3)
ExAws.Config.new(:dynamodb)

    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:29: ExAws.InstanceMeta.request/2
    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:66: ExAws.InstanceMeta.instance_role_credentials/1
    (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:74: ExAws.InstanceMeta.security_credentials/1
    (ex_aws 2.1.7) lib/ex_aws/config/auth_cache.ex:83: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws 2.1.7) lib/ex_aws/config/auth_cache.ex:44: ExAws.Config.AuthCache.handle_call/3
    (stdlib 3.11.2) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib 3.11.2) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from WorldTemp.TempProcessor.Broadway.Producer_0): {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: "localhost", http_client: ExAws.Request.Hackney, json_codec: Jason, normalize_path: true, port: "9324", region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "http://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}
State: ExAws.Config.AuthCache
Client WorldTemp.TempProcessor.Broadway.Producer_0 is alive

    (stdlib 3.11.2) gen.erl:167: :gen.do_call/4
    (elixir 1.10.2) lib/gen_server.ex:1020: GenServer.call/3
    (ex_aws 2.1.7) lib/ex_aws/config.ex:84: ExAws.Config.retrieve_runtime_value/2
    (elixir 1.10.2) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.10.2) lib/enum.ex:3686: Enumerable.List.reduce/3
    (elixir 1.10.2) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.10.2) lib/enum.ex:959: Enum.find/3
    (ex_aws 2.1.7) lib/ex_aws/config.ex:71: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1

11:58:55.777 [error] GenServer WorldTemp.TempProcessor.Broadway.Producer_0 terminating
** (stop) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: "localhost", http_client: ExAws.Request.Hackney, json_codec: Jason, normalize_path: true, port: "9324", region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "http://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}, 30000)
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Instance Meta Error: {:error, %{reason: :timeout}}
You tried to access the AWS EC2 instance meta, but it could not be reached.
This happens most often when trying to access it from your local computer,
which happens when environment variables are not set correctly prompting
ExAws to fallback to the Instance Meta.

Please check your key config and make sure they're configured correctly:

For Example:
ExAws.Config.new(:s3)
ExAws.Config.new(:dynamodb)

            (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:29: ExAws.InstanceMeta.request/2
            (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:66: ExAws.InstanceMeta.instance_role_credentials/1
            (ex_aws 2.1.7) lib/ex_aws/instance_meta.ex:74: ExAws.InstanceMeta.security_credentials/1
            (ex_aws 2.1.7) lib/ex_aws/config/auth_cache.ex:83: ExAws.Config.AuthCache.refresh_config/2
            (ex_aws 2.1.7) lib/ex_aws/config/auth_cache.ex:44: ExAws.Config.AuthCache.handle_call/3
            (stdlib 3.11.2) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib 3.11.2) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir 1.10.2) lib/gen_server.ex:1023: GenServer.call/3
    (ex_aws 2.1.7) lib/ex_aws/config.ex:84: ExAws.Config.retrieve_runtime_value/2
    (elixir 1.10.2) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.10.2) lib/enum.ex:3686: Enumerable.List.reduce/3
    (elixir 1.10.2) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.10.2) lib/enum.ex:959: Enum.find/3
    (ex_aws 2.1.7) lib/ex_aws/config.ex:71: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
    (stdlib 3.11.2) maps.erl:232: :maps.fold_1/3
Last message: {:"$gen_producer", {#PID<0.256.0>, #Reference<0.3265802501.3968860162.121963>}, {:ask, 10}}
State: %{consumers: [{#PID<0.256.0>, #Reference<0.3265802501.3968860162.121963>}], module: BroadwaySQS.Producer, module_state: %{demand: 0, receive_interval: 5000, receive_timer: nil, sqs_client: {BroadwaySQS.ExAwsClient, %{ack_ref: #Reference<0.3265802501.3968860162.121940>, config: [scheme: "http://", host: "localhost", port: "9324"], queue_url: "http://localhost:9324/queue/hi", receive_messages_opts: [max_number_of_messages: 10]}}}, rate_limiting: %{demand_buffer: {[], []}, draining?: false, message_buffer: {[], []}, state: :open, table_name: WorldTemp.TempProcessor.RateLimiter}, transformer: nil}

11:58:55.795 [error] Task #PID<0.92.0> started from #PID<0.275.0> terminating
** (stop) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: "localhost", http_client: ExAws.Request.Hackney, json_codec: Jason, normalize_path: true, port: 9324, region: "elasticmq", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "http://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}, 30000)
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Instance Meta Error: {:error, %{reason: :timeout}}
```

**Comment by philss** [comment] 2021-08-24 13:47
Hey @viniciusd, can you tell us if the problem is solved?
I'm closing the issue for now, since it doesn't seems to be related with Broadway SQS. Feel free to ping us again here :)

**Closed by philss** 2021-08-24 13:47 UTC

**Comment by viniciusd** [comment] 2021-08-29 00:42
> Hey @viniciusd, can you tell us if the problem is solved?
> I'm closing the issue for now, since it doesn't seems to be related with Broadway SQS. Feel free to ping us again here :)

It isn't, but I gave up on using a local ElasticMQ instance and went for a fully-fledged SQS queue as the deadline was approaching.

Thanks you all!
